package com.gdgpune.aroundpune;

import java.io.Serializable;

/**
 * This is POJO class generated by JsonGen to store response coming from Places
 * API
 * 
 * @author Rohit Lagu
 * @version 1.0
 */
@SuppressWarnings("serial")
public class Geometry implements Serializable {
	private Location location;

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}
}
