package com.gdgpune.aroundpune;

import java.io.Serializable;

/**
 * This is POJO class generated by JsonGen to store response coming from Places
 * API
 * 
 * @author Rohit Lagu
 * @version 1.0
 */
@SuppressWarnings("serial")
public class Location implements Serializable {

	/**
	 * Latitude for location
	 */
	private double lat;
	/**
	 * Longitude for location
	 */
	private double lng;

	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public double getLng() {
		return this.lng;
	}

	public void setLng(double lng) {
		this.lng = lng;
	}
}
