package com.gdgpune.aroundpune;

import java.io.Serializable;
import java.util.List;

/**
 * This is POJO class generated by JsonGen to store response coming from Places
 * API
 * 
 * @author Rohit Lagu
 * @version 1.0
 */
@SuppressWarnings("serial")
public class Places implements Serializable {
	@SuppressWarnings("rawtypes")
	private List html_attributions;

	/**
	 * Each element of the results array contains a single result from the
	 * specified area
	 */
	private List<Results> results;
	/**
	 * search response object contains the status of the request
	 * <p>
	 * OK indicates that no errors occurred; the place was successfully detected
	 * and at least one result was returned.
	 * <p>
	 * ZERO_RESULTS indicates that the search was successful but returned no
	 * results. This may occur if the search was passed a latlng in a remote
	 * location.
	 * <p>
	 * OVER_QUERY_LIMIT indicates that you are over your quota.
	 * <p>
	 * REQUEST_DENIED indicates that your request was denied, generally because
	 * of lack of a sensor parameter.
	 * <p>
	 * INVALID_REQUEST generally indicates that a required query parameter
	 * (location or radius) is missing.
	 */
	private String status;

	@SuppressWarnings("rawtypes")
	public List getHtml_attributions() {
		return this.html_attributions;
	}

	public void setHtml_attributions(
			@SuppressWarnings("rawtypes") List html_attributions) {
		this.html_attributions = html_attributions;
	}

	public List<Results> getResults() {
		return this.results;
	}

	public void setResults(List<Results> results) {
		this.results = results;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
